version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: scikit-learn
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
